{{- $securityEnabled := eq (toString .Values.security.enabled) "true" -}}
{{- if $securityEnabled -}}
  {{- $validation := .Values.security.defaultUserEmail | required "security.defaultUserEmail is required." -}}
  {{- $validation := .Values.security.defaultUserName | required "security.defaultUserName is required." -}}
  {{- $validation := .Values.security.jwt.secret | required "security.jwt.secret is required." -}}
  {{- $validation := .Values.workers.accessKeyId | required "workers.accessKeyId is required." -}}
  {{- $validation := .Values.workers.accessKeySecret | required "workers.accessKeySecret is required." -}}
  {{- if .Values.security.auth0 -}}
    {{- $validation := .Values.security.auth0.clientId | required "security.auth0.clientId is required." -}}
    {{- $validation := .Values.security.auth0.domain | required ".security.auth0.domain is required." -}}
    {{- if eq (toString .Values.security.auth0.useIdToken) "false" -}}
      {{- $validation := .Values.security.auth0.clientSecret | required "security.auth0.clientSecret is required if useIdToken is false." -}}
    {{- end -}}
  {{- end -}}
  {{- if .Values.security.oidc -}}
    {{- $validation := .Values.security.oidc.clientId | required "security.oidc.clientId is required." -}}
    {{- $validation := .Values.security.oidc.audience | required "security.oidc.audience is required." -}}
    {{- $validation := .Values.security.oidc.metadataUrl | required "security.oidc.metadataUrl is required." -}}
  {{- end -}}
  {{- if .Values.security.okta -}}
    {{- $validation := .Values.security.okta.clientId | required "security.okta.clientId is required." -}}
    {{- $validation := .Values.security.okta.audience | required "security.okta.audience is required." -}}
    {{- $validation := .Values.security.okta.issuer | required "security.okta.issuer is required." -}}
  {{- end -}}
{{- end -}}
{{- if eq .Values.app.archiveStoreType "s3" -}}
  {{- $validation := .Values.app.documentStoreS3BucketName | required "app.documentStoreS3BucketName is required." -}}
{{- end -}}
{{- if eq .Values.app.archiveStoreType "azureblob" -}}
  {{- $validation := .Values.app.documentStoreAzureBlobContainerName | required "app.documentStoreAzureBlobContainerName is required." -}}
  {{- $validation := .Values.app.documentStoreAzureBlobEndpoint | required "app.documentStoreAzureBlobEndpoint is required." -}}
{{- end -}}
{{- $redisPassword := printf "redis12" }}
{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" .Release.Namespace "orkesdeploymentsecrets") }}
{{- if $secret.data.redispassword }}
  {{- $redisPassword := $secret.data.redispassword | b64dec }}
{{- end }}
{{- $redisHosts := printf "%v:%v:%v" .Values.redis.host .Values.redis.port "us-east" -}}
{{- if $redisPassword -}}
  {{- $redisHosts = printf "%v:%v" $redisHosts $redisPassword -}}
{{- end -}}
{{- $redisUriScheme := .Values.redis.ssl | ternary "rediss" "redis" -}}
{{- $redisLockServerAddress := printf "%v://%v:%v" $redisUriScheme .Values.redis.host .Values.redis.port -}}
{{- /*
  The variables below exist for backwards compatibility
*/}}
{{- $appReplicaCount := .Values.app.replicaCount | default .Values.replicaCount -}}
{{- $validation := $appReplicaCount | required "replicaCount (deprecated) or app.replicaCount is required." -}}
{{- $secretsType := .Values.secrets.type | default .Values.app.secretsType -}}
{{- $validation := $secretsType | required "app.secretsType (deprecated) or secrets.type is required." -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orkes-conductor.fullname" . }}
  labels:
    {{- include "orkes-conductor.labels" . | nindent 4 }}
spec:
  replicas: {{ $appReplicaCount }}
  selector:
    matchLabels:
      {{- include "orkes-conductor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        {{- include "orkes-conductor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            #### Env ####
            - name: cloud.env
              value: {{ .Values.app.env }}
            - name: DEPLOY_ENV
              value: prod
            - name: aws.region
              value: {{ .Values.app.s3Region | quote }}
            - name: JVM_MEMORY_SETTINGS
              value: {{ .Values.app.jvmSettings | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.springProfilesActive | quote }}
            #### Redis ####
            - name: conductor.redis.hosts
              value: {{ $redisHosts | quote }}
            - name: conductor.redis.ssl
              value: {{ .Values.redis.ssl | quote }}
            - name: conductor.redis-lock.serverAddress
              value: {{ $redisLockServerAddress | quote }}
            {{- if .Values.redis.password }}
            - name: conductor.redis-lock.serverPassword
              value: {{ .Values.redis.password }}
            {{- end }}
            #### Postgres ####
            - name: spring.datasource.url
              value: {{ .Values.postgres.url | quote }}
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: orkesdeploymentsecrets
                  key: postgrespassword
            - name: spring.datasource.username
              value: {{ .Values.postgres.username | quote }}
            {{- if $securityEnabled }}
            #### Security ####
            - name: conductor.security.enabled
              value: "true"
            - name: conductor.security.default.overwrite
              value: {{ .Values.security.overwriteDefault | quote }}
            - name: conductor.security.default.users.0.email
              value: {{ .Values.security.defaultUserEmail | quote }}
            - name: conductor.security.default.users.0.name
              value: {{ .Values.security.defaultUserName | quote }}
            - name: conductor.security.default.users.0.role
              value: "ADMIN"
            - name: conductor.security.default.createUserOnAuthentication
              value: {{ .Values.security.createUserOnAuthentication | quote }}
            - name: conductor.security.default.workers.accessKeyId
              value: {{ .Values.workers.accessKeyId | quote }}
            - name: conductor.security.default.workers.accessKeySecret
              value: {{ .Values.workers.accessKeySecret | quote }}
            - name: conductor.security.jwt.secret
              valueFrom:
                secretKeyRef:
                  name: orkesdeploymentsecrets
                  key: jwtsecret
            {{- if .Values.security.auth0 }}
            #### Security - Auth0 ####
            - name: conductor.security.auth0.clientId
              value: {{ .Values.security.auth0.clientId | quote }}
            {{- if .Values.security.auth0.clientSecret }}
            - name: conductor.security.auth0.clientSecret
#              value: {{ .Values.security.auth0.clientSecret | quote }}
              valueFrom:
                secretKeyRef:
                  name: orkesdeploymentsecrets
                  key: clientsecret
            {{- end }}
            - name: conductor.security.auth0.useIdToken
              value: {{ ne (toString .Values.security.auth0.useIdToken) "false" | quote }}
            - name: conductor.security.auth0.domain
              value: {{ .Values.security.auth0.domain | quote }}
            {{- end }}
            {{- if .Values.security.oidc }}
            #### Security - OIDC ####
            - name: conductor.security.oidc.clientId
              value: {{ .Values.security.oidc.clientId | quote }}
            - name: conductor.security.oidc.audience
              value: {{ .Values.security.oidc.audience | quote }}
            - name: conductor.security.oidc.metadataUrl
              value: {{ .Values.security.oidc.metadataUrl | quote }}
            - name: conductor.security.oidc.claims.email
              value: {{ .Values.security.oidc.emailClaim | quote }}
            {{- end }}
            {{- if .Values.security.okta }}
            #### Security - OKTA ####
            - name: conductor.security.okta.clientId
              value: {{ .Values.security.okta.clientId | quote }}
            - name: conductor.security.okta.audience
              value: {{ .Values.security.okta.audience | quote }}
            - name: conductor.security.okta.issuer
              value: {{ .Values.security.okta.issuer | quote }}
            - name: conductor.security.okta.useInteractionCodeFlow
              value: {{ .Values.security.okta.useInteractionCodeFlow | quote }}
            {{- if .Values.security.okta.idpConf }}
            - name: conductor.security.okta.idpConf
              value: {{ .Values.security.okta.idpConf }}
            {{- end }}
            {{- if .Values.security.okta.sync }}
            - name: conductor.security.okta.sync.enabled
              value: "true"
            {{- if .Values.security.okta.sync.frequency }}
            - name: conductor.security.okta.sync.frequency
              value: {{ .Values.security.okta.sync.frequency | quote }}
            {{- end }}
            - name: conductor.security.okta.sync.org
              value: {{ .Values.security.okta.sync.org }}
            - name: conductor.security.okta.sync.clientId
              value: {{ .Values.security.okta.sync.clientId }}
            - name: conductor.security.okta.sync.privateKey
#              value: {{- .Values.security.okta.sync.privateKey | toYaml | indent 14 }}
              valueFrom:
                secretKeyRef:
                  name: orkesdeploymentsecrets
                  key: privatekey
            {{- end }}
            {{- end }}
            {{- end }}
            #### Archive ####
            - name: conductor.archive.db.document.store.type
              value: {{ .Values.app.archiveStoreType | quote }}
            - name: conductor.archive.db.document.store.s3.region
              value: {{ .Values.app.s3Region }}
            - name: conductor.archive.db.document.store.uploader.threadCount
              value: {{ .Values.app.documentStoreUploaderThreadCount | quote }}
            - name: conductor.archive.db.indexer.threadCount
              value: {{ .Values.app.dbIndexerThreadCount | quote }}
            - name: conductor.archive.db.indexer.pollingInterval
              value: {{ .Values.app.dbIndexerPollingInterval | quote }}
            {{- if eq .Values.app.archiveStoreType "s3" }}
            - name: conductor.archive.db.document.store.s3.s3BucketName
              value: {{ .Values.app.documentStoreS3BucketName | quote }}
            {{- end }}
            {{- if eq .Values.app.archiveStoreType "azureblob" }}
            - name: conductor.archive.db.document.store.type.azureblob.containerName
              value: {{ .Values.app.documentStoreAzureBlobContainerName | quote }}
            - name: conductor.archive.db.document.store.type.azureblob.endpoint
              value: {{ .Values.app.documentStoreAzureBlobEndpoint | quote }}
            {{- end }}
            - name: conductor.archive.db.indexer.pollBatchSize
              value: {{ .Values.app.dbIndexerPollBatchSize | quote }}
            #### Sweeper ####
            - name: conductor.app.sweeper.sweepBatchSize
              value: {{ .Values.app.sweepBatchSize | quote }}
            - name: conductor.app.sweeperThreadCount
              value: {{ .Values.app.sweeperThreadCount | quote }}
            - name: conductor.sweep-frequency.millis
              value: {{ .Values.app.sweepFrequencyMillis | quote }}
            #### Scheduler ####
            - name: conductor.scheduler.pollBatchSize
              value: {{ .Values.app.schedulerPollBatchSize | quote }}
            - name: conductor.scheduler.pollingInterval
              value: {{ .Values.app.schedulerPollingInterval | quote }}
            #### Secrets ####
            - name: conductor.secrets.type
              value: {{ $secretsType | quote }}
            {{- if .Values.secrets.ssmPath }}
            - name: conductor.secrets.ssm.path
              value: {{ .Values.secrets.ssmPath | quote }}
            {{- end }}
            #### Others ####
            - name: conductor.swagger.url
              value: {{ .Values.app.swaggerUrl | quote }}
            - name: conductor.app.lockTimeToTry
              value: {{ .Values.app.lockTimeToTry | quote }}
            - name: conductor.app.systemTaskMaxPollCount
              value: {{ .Values.app.systemTaskMaxPollCount | quote }}
            - name: conductor.app.workflow-execution-lock-enabled
              value: {{ .Values.app.workflowExecutionLockEnabled | quote }}
            - name: conductor.api.ratelimiter.enabled
              value: {{ .Values.app.apiRateLimiterEnabled | quote }}
            - name: LOCAL_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.image.livenessPort }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.app.resources.cpuLimit | quote }}
              memory: {{ .Values.app.resources.memoryLimit | quote }}
            requests:
              cpu: {{ .Values.app.resources.cpuRequests | quote }}
              memory: {{ .Values.app.resources.memoryRequests | quote }}
          startupProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: orkesregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: conductor-app
      serviceAccountName: conductor-app
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orkes-conductor-workers.fullname" . }}-workers
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.workers.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ include "orkes-conductor-workers.fullname" . }}-workers
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        app: {{ include "orkes-conductor-workers.fullname" . }}-workers
    spec:
      containers:
        - env:
            - name: DEPLOY_ENV
              value: prod
            - name: JVM_MEMORY_SETTINGS
              value: {{ .Values.workers.jvmSettings | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.workers.springProfilesActive | quote }}
            - name: conductor.worker.http.block.hosts
              value: localhost
            - name: conductor.worker.http.block.ips
              value: {{ .Values.workers.blockIps | quote }}
            - name: conductor.server.url
              value: http://{{ include "orkes-conductor.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5000/api/
            {{- if $securityEnabled }}
            - name: conductor.security.client.key-id
              value: {{ .Values.workers.accessKeyId | quote }}
            - name: conductor.security.client.secret
              value: {{ .Values.workers.accessKeySecret | quote }}
            {{- end }}
            - name: LOCAL_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "{{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ include "orkes-conductor-workers.fullname" . }}-workers
          resources:
            limits:
              cpu: {{ .Values.workers.resources.cpuLimit | quote }}
              memory: {{ .Values.workers.resources.memoryLimit | quote }}
            requests:
              cpu: {{ .Values.workers.resources.cpuRequests | quote }}
              memory: {{ .Values.workers.resources.memoryRequests | quote }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: orkesregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: conductor-workers-app
      serviceAccountName: conductor-workers-app
      terminationGracePeriodSeconds: 30