{{- $redisHosts := printf "%v:%v:%v" .Values.redis.host .Values.redis.port "us-east-1c" -}}
{{- if .Values.redis.password -}}
  {{- $redisHosts = printf "%v:%v" $redisHosts .Values.redis.password -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: orkesregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---
apiVersion: v1
kind: Secret
metadata:
  name: orkesdeploymentsecrets
type: kubernetes.io/dockerconfigjson
data:
  redis:
    password: {{ default "" .Values.redis.password | quote }}
  redisHosts: {{ $redisHosts | quote }}
  postgres:
    password: {{ default "" .Values.postgres.password | quote }}