apiVersion: v1
kind: Secret
metadata:
  name: orkesregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: orkesdeploymentsecrets
type: Opaque
data:
  postgrespassword: cG9zdGdyZXMxMjM=
# Secret used to sign JWTs. How to generate it? openssl rand -base64 172 | tr -d '\n'
  jwtsecret: ""
  privatekey:
# clientSecret is only needed if useIdToken: false
  clientsecret:
  