{{- $redisHosts := printf "%v:%v:%v" .Values.redis.host .Values.redis.port "us-east-1c" -}}
{{- if .Values.redis.password -}}
{{- $redisHosts = printf "%v:%v" $redisHosts .Values.redis.password -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: orkesregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: orkesdeploymentsecrets
type: Opaque
data:
  redisHosts: {{ $redisHosts | quote }}
  redisPassword: {{ .Values.redis.password | quote }}
  postgresPassword: {{ .Values.postgres.password | quote }}
  securityJwtSecret: {{ .Values.security.jwt.secret | quote }}
  auth0ClientSecret: {{ .Values.security.auth0.clientSecret | quote }}
  oktaSyncPrivateKey: ""
