apiVersion: v1
kind: ServiceAccount
metadata:
  name: conductor-app
  labels:
    {{- include "orkes-conductor.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conductor-workers-app
  labels:
    {{- include "orkes-conductor.labels" . | nindent 4 }}